version: '3'

services:
  db:
    image: mongo:5
    container_name: nest-pokemon-db
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongo:/data/db